M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu22.04.1} date Thu 26 May 2022 03:12:16 AM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-26T03:12:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0205
%
G90
G05
T1
X2.3524Y-2.8937
X2.6476Y-2.8937
T0
M30
